# Generated by Django 5.0.6 on 2026-07-19 20:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80, unique=True)),
                ('pais_origen', models.CharField(max_length=60)),
                ('anio_fundacion', models.IntegerField(help_text='Año en que se fundó la marca')),
            ],
            options={
                'verbose_name': 'Marca',
                'verbose_name_plural': 'Marcas',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='AutoDeportivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(max_length=100)),
                ('anio', models.IntegerField(help_text='Año del modelo')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fecha_adquisicion', models.DateField()),
                ('color', models.CharField(max_length=40)),
                ('categoria', models.CharField(choices=[('SUP', 'Superdeportivo'), ('GT', 'Gran Turismo'), ('CLA', 'Clásico'), ('HYP', 'Hypercar')], default='SUP', max_length=3)),
                ('imagen_url', models.URLField(blank=True, null=True)),
                ('notas', models.TextField(blank=True)),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='autos', to='garage.marca')),
            ],
            options={
                'verbose_name': 'Auto deportivo',
                'verbose_name_plural': 'Autos deportivos',
                'ordering': ['-fecha_adquisicion'],
            },
        ),
    ]
