# Generated by Django 5.0.6 on 2026-07-23 22:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Propietario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('ciudad', models.CharField(blank=True, max_length=80)),
            ],
            options={
                'verbose_name': 'Propietario',
                'verbose_name_plural': 'Propietarios',
                'db_table': 'garage_propietario',
                'ordering': ['nombre'],
            },
        ),
        migrations.AlterModelTable(
            name='autodeportivo',
            table='garage_autodeportivo',
        ),
        migrations.AlterModelTable(
            name='marca',
            table='garage_marca',
        ),
        migrations.CreateModel(
            name='Mantenimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_servicio', models.DateField()),
                ('tipo_servicio', models.CharField(choices=[('AFI', 'Afinación'), ('ACE', 'Cambio de aceite'), ('FRE', 'Frenos'), ('CAR', 'Carrocería / pintura'), ('REV', 'Revisión general'), ('OTR', 'Otro')], default='REV', max_length=3)),
                ('costo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('taller', models.CharField(max_length=100)),
                ('notas', models.TextField(blank=True)),
                ('auto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mantenimientos', to='garage.autodeportivo')),
            ],
            options={
                'verbose_name': 'Mantenimiento',
                'verbose_name_plural': 'Mantenimientos',
                'db_table': 'garage_mantenimiento',
                'ordering': ['-fecha_servicio'],
            },
        ),
        migrations.AddField(
            model_name='autodeportivo',
            name='propietario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='autos', to='garage.propietario'),
        ),
    ]
